var searchData=
[
  ['salt_5flen_0',['SALT_LEN',['../key__derivation_8h.html#a531df3ddc06621690d3ea6e7e05a4e62',1,'key_derivation.h']]],
  ['sanitizers_1',['Dynamic Analysis (Sanitizers)',['../md_docs_2TESTING.html#autotoc_md104',1,'']]],
  ['save_5fsalt_2',['save_salt',['../key__derivation_8c.html#a64c3fb401d2807bb3f207e7c60f150c1',1,'save_salt(const char *path, const uint8_t *salt):&#160;key_derivation.c'],['../key__derivation_8h.html#a64c3fb401d2807bb3f207e7c60f150c1',1,'save_salt(const char *path, const uint8_t *salt):&#160;key_derivation.c']]],
  ['scope_3',['Scope',['../md_CODE__OF__CONDUCT.html#autotoc_md56',1,'']]],
  ['secure_20build_20process_4',['Secure Build Process',['../md_SECURITY.html#autotoc_md40',1,'']]],
  ['securepasswd_5fmgmt_5',['securepasswd_mgmt',['../md_CONTRIBUTING.html',1,'Contributing to SecurePasswd_MGMT'],['../index.html',1,'SecurePasswd_MGMT']]],
  ['security_6',['security',['../md_SECURITY.html#autotoc_md39',1,'File System Security'],['../md_CHANGELOG.html#autotoc_md83',1,'Security'],['../md_CHANGELOG.html#autotoc_md79',1,'Security'],['../md_CHANGELOG.html#autotoc_md74',1,'Security'],['../md_CHANGELOG.html#autotoc_md72',1,'Security'],['../md_CHANGELOG.html#autotoc_md69',1,'Security'],['../index.html#autotoc_md19',1,'Security']]],
  ['security_20features_7',['Key Security Features',['../index.html#autotoc_md1',1,'']]],
  ['security_20flow_8',['Master Password Security Flow',['../md_SECURITY.html#autotoc_md35',1,'']]],
  ['security_20focused_20development_9',['Security-Focused Development',['../md_CONTRIBUTING.html#autotoc_md46',1,'']]],
  ['security_20goals_10',['Security Goals',['../md_SECURITY.html#autotoc_md27',1,'']]],
  ['security_20overview_11',['Security Overview',['../md_SECURITY.html#autotoc_md26',1,'']]],
  ['security_20policy_12',['Security Policy',['../md_SECURITY.html',1,'']]],
  ['security_20validation_13',['Input Security &amp; Validation',['../md_SECURITY.html#autotoc_md33',1,'']]],
  ['security_20verification_14',['Security Verification',['../md_docs_2TESTING.html#autotoc_md102',1,'']]],
  ['security_20vulnerabilities_15',['Reporting Security Vulnerabilities',['../md_SECURITY.html#autotoc_md44',1,'']]],
  ['security_2emd_16',['SECURITY.md',['../SECURITY_8md.html',1,'']]],
  ['service_17',['service',['../structPasswordEntry.html#a7efd3f2f980acb7d38669e9074f4a85a',1,'PasswordEntry']]],
  ['services_18',['Hashing for External Services',['../md_SECURITY.html#autotoc_md32',1,'']]],
  ['size_19',['size',['../structMemoryStruct.html#a79d6a7ad34b172f766c19d0846688440',1,'MemoryStruct']]],
  ['source_20',['Build from Source',['../index.html#autotoc_md11',1,'']]],
  ['standards_21',['Our Standards',['../md_CODE__OF__CONDUCT.html#autotoc_md54',1,'']]],
  ['static_20analysis_22',['Static Analysis',['../md_docs_2TESTING.html#autotoc_md103',1,'']]],
  ['status_3a_20✓_20pass_20multi_20platform_23',['Build Status: ✓ PASS (Multi-Platform)',['../md_docs_2TESTING.html#autotoc_md101',1,'']]],
  ['storage_20format_24',['Data Storage Format',['../md_SECURITY.html#autotoc_md36',1,'']]],
  ['strength_20validation_25',['Password Strength Validation',['../md_SECURITY.html#autotoc_md41',1,'']]],
  ['structure_26',['Project Structure',['../index.html#autotoc_md20',1,'']]],
  ['style_27',['Coding Style',['../md_CONTRIBUTING.html#autotoc_md48',1,'']]],
  ['summary_28',['summary',['../md_docs_2TESTING.html#autotoc_md106',1,'Test Summary'],['../md_docs_2TESTING.html',1,'Testing and Verification Summary']]],
  ['sync_29',['Cross-Platform Sync',['../index.html#autotoc_md5',1,'']]],
  ['sync_5fdecrypt_5fvault_30',['sync_decrypt_vault',['../sync__service_8h.html#abce18545611bf6817b55518f3ea649b9',1,'sync_decrypt_vault(const unsigned char *encrypted_data, size_t data_len, const char *db_path, const unsigned char key[SYNC_KEY_LEN]):&#160;sync_service.c'],['../sync__service_8c.html#abce18545611bf6817b55518f3ea649b9',1,'sync_decrypt_vault(const unsigned char *encrypted_data, size_t data_len, const char *db_path, const unsigned char key[SYNC_KEY_LEN]):&#160;sync_service.c']]],
  ['sync_5fencrypt_5fvault_31',['sync_encrypt_vault',['../sync__service_8h.html#a282c8efccb953d64e16e3394af1a1f98',1,'sync_encrypt_vault(const char *db_path, unsigned char *output_buffer, size_t *output_size, const unsigned char key[SYNC_KEY_LEN]):&#160;sync_service.c'],['../sync__service_8c.html#a282c8efccb953d64e16e3394af1a1f98',1,'sync_encrypt_vault(const char *db_path, unsigned char *output_buffer, size_t *output_size, const unsigned char key[SYNC_KEY_LEN]):&#160;sync_service.c']]],
  ['sync_5fkey_5flen_32',['SYNC_KEY_LEN',['../sync__service_8h.html#ae08a140233b2de8b24e4ba7967c4bf2a',1,'sync_service.h']]],
  ['sync_5fnonce_5flen_33',['SYNC_NONCE_LEN',['../sync__service_8h.html#aa441e9db64dff745c3e1fd3b94a47606',1,'sync_service.h']]],
  ['sync_5fservice_2ec_34',['sync_service.c',['../sync__service_8c.html',1,'']]],
  ['sync_5fservice_2eh_35',['sync_service.h',['../sync__service_8h.html',1,'']]],
  ['sync_5ftag_5flen_36',['SYNC_TAG_LEN',['../sync__service_8h.html#a77cb9ae25ecd65b46d6e3f24abd18869',1,'sync_service.h']]],
  ['system_20security_37',['File System Security',['../md_SECURITY.html#autotoc_md39',1,'']]]
];
