var searchData=
[
  ['categories_20legend_0',['Categories Legend',['../md_CHANGELOG.html#autotoc_md93',1,'']]],
  ['changed_1',['changed',['../md_CHANGELOG.html#autotoc_md65',1,'Changed'],['../md_CHANGELOG.html#autotoc_md88',1,'Changed'],['../md_CHANGELOG.html#autotoc_md83',1,'Changed']]],
  ['changelog_2',['Changelog',['../md_CHANGELOG.html',1,'']]],
  ['changelog_2emd_3',['CHANGELOG.md',['../CHANGELOG_8md.html',1,'']]],
  ['check_20requirements_4',['Health Check Requirements',['../md_SECURITY.html#autotoc_md41',1,'']]],
  ['citation_2ecff_5',['CITATION.cff',['../CITATION_8cff.html',1,'']]],
  ['cli_6',['Command-Line Interface (CLI)',['../index.html#autotoc_md3',1,'']]],
  ['cli_20only_20build_20no_20gui_7',['CLI-Only Build (No GUI)',['../index.html#autotoc_md13',1,'']]],
  ['code_20of_20conduct_8',['code of conduct',['../index.html#autotoc_md23',1,'Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Contributor Covenant Code of Conduct']]],
  ['code_20review_9',['Code Review',['../md_CONTRIBUTING.html#autotoc_md46',1,'']]],
  ['code_5fof_5fconduct_2emd_10',['CODE_OF_CONDUCT.md',['../CODE__OF__CONDUCT_8md.html',1,'']]],
  ['coding_20style_11',['Coding Style',['../md_CONTRIBUTING.html#autotoc_md47',1,'']]],
  ['command_20line_20interface_12',['Command-Line Interface',['../index.html#autotoc_md18',1,'']]],
  ['command_20line_20interface_20cli_13',['Command-Line Interface (CLI)',['../index.html#autotoc_md3',1,'']]],
  ['compliance_14',['Compliance',['../md_SECURITY.html#autotoc_md42',1,'']]],
  ['conduct_15',['conduct',['../index.html#autotoc_md23',1,'Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Contributor Covenant Code of Conduct']]],
  ['contribute_16',['How to Contribute',['../md_CONTRIBUTING.html#autotoc_md49',1,'']]],
  ['contributing_20to_20securepasswd_5fmgmt_17',['Contributing to SecurePasswd_MGMT',['../md_CONTRIBUTING.html',1,'']]],
  ['contributing_2emd_18',['CONTRIBUTING.md',['../CONTRIBUTING_8md.html',1,'']]],
  ['contribution_19',['Contribution',['../index.html#autotoc_md22',1,'']]],
  ['contributor_20covenant_20code_20of_20conduct_20',['Contributor Covenant Code of Conduct',['../md_CODE__OF__CONDUCT.html',1,'']]],
  ['contributors_21',['Contributors',['../md_AUTHORS.html#autotoc_md60',1,'']]],
  ['core_20team_22',['Core Team',['../md_AUTHORS.html#autotoc_md59',1,'']]],
  ['core_20tests_20tt_20core_5ftests_20tt_23',['Core Tests (&lt;tt&gt;./core_tests&lt;/tt&gt;)',['../md_docs_2TESTING.html#autotoc_md103',1,'']]],
  ['core_5ftests_20tt_24',['Core Tests (&lt;tt&gt;./core_tests&lt;/tt&gt;)',['../md_docs_2TESTING.html#autotoc_md103',1,'']]],
  ['covenant_20code_20of_20conduct_25',['Contributor Covenant Code of Conduct',['../md_CODE__OF__CONDUCT.html',1,'']]],
  ['cross_20platform_20sync_26',['Cross-Platform Sync',['../index.html#autotoc_md5',1,'']]],
  ['cryptographic_20implementation_27',['Cryptographic Implementation',['../md_SECURITY.html#autotoc_md28',1,'']]],
  ['current_5fdb_5fpath_28',['current_db_path',['../database_8c.html#a98d73fa89d982dfc8d1461333d94f668',1,'database.c']]]
];
