var searchData=
[
  ['salt_5flen_0',['SALT_LEN',['../key__derivation_8h.html#a531df3ddc06621690d3ea6e7e05a4e62',1,'key_derivation.h']]],
  ['sanitize_5fpath_1',['sanitize_path',['../platform__paths_8c.html#a5339ed1fb4e7ecf92035c7f251061991',1,'platform_paths.c']]],
  ['sanitizers_2',['Dynamic Analysis (Sanitizers)',['../md_docs_2TESTING.html#autotoc_md95',1,'']]],
  ['save_5fsalt_3',['save_salt',['../key__derivation_8c.html#a64c3fb401d2807bb3f207e7c60f150c1',1,'save_salt(const char *path, const uint8_t *salt):&#160;key_derivation.c'],['../key__derivation_8h.html#a64c3fb401d2807bb3f207e7c60f150c1',1,'save_salt(const char *path, const uint8_t *salt):&#160;key_derivation.c']]],
  ['scope_4',['Scope',['../md_CODE__OF__CONDUCT.html#autotoc_md54',1,'']]],
  ['secure_20build_20process_5',['Secure Build Process',['../md_SECURITY.html#autotoc_md38',1,'']]],
  ['securepasswd_5fmgmt_6',['securepasswd_mgmt',['../md_CONTRIBUTING.html',1,'Contributing to SecurePasswd_MGMT'],['../index.html',1,'SecurePasswd_MGMT']]],
  ['security_7',['security',['../md_SECURITY.html#autotoc_md37',1,'File System Security'],['../md_CHANGELOG.html#autotoc_md73',1,'Security'],['../md_CHANGELOG.html#autotoc_md63',1,'Security'],['../md_CHANGELOG.html#autotoc_md66',1,'Security'],['../md_CHANGELOG.html#autotoc_md68',1,'Security'],['../index.html#autotoc_md18',1,'Security']]],
  ['security_20features_8',['Key Security Features',['../index.html#autotoc_md1',1,'']]],
  ['security_20flow_9',['Master Password Security Flow',['../md_SECURITY.html#autotoc_md34',1,'']]],
  ['security_20focused_20development_10',['Security-Focused Development',['../md_CONTRIBUTING.html#autotoc_md44',1,'']]],
  ['security_20goals_11',['Security Goals',['../md_SECURITY.html#autotoc_md26',1,'']]],
  ['security_20overview_12',['Security Overview',['../md_SECURITY.html#autotoc_md25',1,'']]],
  ['security_20policy_13',['Security Policy',['../md_SECURITY.html',1,'']]],
  ['security_20validation_14',['Input Security &amp; Validation',['../md_SECURITY.html#autotoc_md32',1,'']]],
  ['security_20verification_15',['Security Verification',['../md_docs_2TESTING.html#autotoc_md93',1,'']]],
  ['security_20vulnerabilities_16',['Reporting Security Vulnerabilities',['../md_SECURITY.html#autotoc_md42',1,'']]],
  ['security_2emd_17',['SECURITY.md',['../SECURITY_8md.html',1,'']]],
  ['service_18',['service',['../structPasswordEntry.html#a7efd3f2f980acb7d38669e9074f4a85a',1,'PasswordEntry']]],
  ['services_19',['Hashing for External Services',['../md_SECURITY.html#autotoc_md31',1,'']]],
  ['size_20',['size',['../structMemoryStruct.html#a79d6a7ad34b172f766c19d0846688440',1,'MemoryStruct']]],
  ['source_21',['Build from Source',['../index.html#autotoc_md10',1,'']]],
  ['standards_22',['Our Standards',['../md_CODE__OF__CONDUCT.html#autotoc_md52',1,'']]],
  ['static_20analysis_23',['Static Analysis',['../md_docs_2TESTING.html#autotoc_md94',1,'']]],
  ['status_3a_20✓_20pass_24',['Build Status: ✓ PASS',['../md_docs_2TESTING.html#autotoc_md92',1,'']]],
  ['storage_20format_25',['Data Storage Format',['../md_SECURITY.html#autotoc_md35',1,'']]],
  ['strength_20validation_26',['Password Strength Validation',['../md_SECURITY.html#autotoc_md39',1,'']]],
  ['structure_27',['Project Structure',['../index.html#autotoc_md19',1,'']]],
  ['style_28',['Coding Style',['../md_CONTRIBUTING.html#autotoc_md46',1,'']]],
  ['summary_29',['summary',['../md_docs_2TESTING.html#autotoc_md97',1,'Test Summary'],['../md_docs_2TESTING.html',1,'Testing and Verification Summary']]],
  ['system_20security_30',['File System Security',['../md_SECURITY.html#autotoc_md37',1,'']]]
];
