name: Release SecurePasswd_MGMT

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: debian-package
            package_glob: "*.deb"
            cpack_generator: "DEB"
          - os: windows-latest
            artifact_name: windows-installer
            package_glob: "*.exe"
            cpack_generator: "NSIS"
          - os: macos-latest
            artifact_name: macos-dmg
            package_glob: "*.dmg"
            cpack_generator: "DragNDrop"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the version
        id: get_version
        shell: bash
        run: echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Create source tarball
        if: runner.os == 'Linux'
        run: |
          cd ..
          tar -czvf securepasswd_mgmt-${{ steps.get_version.outputs.version }}.tar.gz \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="*.tar.gz" \
            SecurePasswd_MGMT/
          mv securepasswd_mgmt-${{ steps.get_version.outputs.version }}.tar.gz SecurePasswd_MGMT/

      - name: Upload source tarball
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: source-tarball
          path: securepasswd_mgmt-${{ steps.get_version.outputs.version }}.tar.gz

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libsodium-dev libargon2-dev libsqlcipher-dev libcsv-dev qt6-base-dev libssl-dev libcurl4-openssl-dev

      - name: Cache vcpkg
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        with:
          path: vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: ${{ runner.os }}-vcpkg-

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          if (-not (Test-Path vcpkg)) {
            git clone https://github.com/Microsoft/vcpkg.git
            .\vcpkg\bootstrap-vcpkg.bat
          }
          .\vcpkg\vcpkg install libsodium argon2 curl openssl --triplet x64-windows

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          # Update brew first
          brew update

          # Install packages with retry logic
          packages="qt@6 create-dmg libsodium argon2 sqlcipher openssl curl"
          for pkg in $packages; do
            brew list $pkg &>/dev/null || brew install $pkg || echo "Failed to install $pkg, continuing..."
          done

      - name: Install libcsv from source (macOS)
        if: runner.os == 'macOS'
        run: |
          git clone https://github.com/rgamble/libcsv.git
          cd libcsv
          make
          sudo make install
        continue-on-error: true

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCPACK_PACKAGE_VERSION=${{ steps.get_version.outputs.version }} -DPROJECT_VERSION=${{ steps.get_version.outputs.version }} -DCPACK_GENERATOR=${{ matrix.cpack_generator }}

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        working-directory: build
        run: cpack -G ${{ matrix.cpack_generator }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: build/${{ matrix.package_glob }}

  build-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
    needs: build
    steps:
      - name: Get the version
        id: get_version
        run: echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Download source tarball
        uses: actions/download-artifact@v4
        with:
          name: source-tarball

      - name: Install build tools and dependencies
        run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm git base-devel libsodium argon2 sqlcipher qt6-base openssl curl cmake

      - name: Install libcsv from source (Arch)
        run: |
          git clone https://github.com/rgamble/libcsv.git
          cd libcsv
          make
          make install
        continue-on-error: true

      - name: Extract source tarball
        run: |
          tar -xzvf securepasswd_mgmt-${{ steps.get_version.outputs.version }}.tar.gz

      - name: Create PKGBUILD
        run: |
          sha256=$(sha256sum securepasswd_mgmt-${{ steps.get_version.outputs.version }}.tar.gz | awk '{print $1}')
          cat <<EOF > PKGBUILD
          # Maintainer: fam007e <faisalmoshiur+secpasswdmgmt@gmail.com>
          pkgname=securepasswd_mgmt
          pkgver=${{ steps.get_version.outputs.version }}
          pkgrel=1
          pkgdesc="A secure, cross-platform password manager with TOTP support."
          arch=('x86_64')
          url="https://github.com/fam007e/SecurePasswd_MGMT"
          license=('MIT')
          depends=('libsodium' 'argon2' 'sqlcipher' 'qt6-base' 'libcsv' 'openssl' 'curl')
          makedepends=('cmake' 'gcc')
          source=("\$pkgname-\$pkgver.tar.gz")
          sha256sums=("$sha256")

          build() {
              cd "\$srcdir/SecurePasswd_MGMT"
              mkdir -p build
              cd build
              cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
              make
          }

          package() {
              cd "\$srcdir/SecurePasswd_MGMT/build"
              make DESTDIR="\$pkgdir/" install
          }
          EOF

      - name: Build Arch package
        run: |
          useradd -m builder
          chown -R builder:builder .
          su - builder -c "cd $(pwd) && makepkg -s --noconfirm"

      - name: Upload Arch package
        uses: actions/upload-artifact@v4
        with:
          name: arch-package
          path: "*.pkg.tar.zst"

  release:
    needs: [build, build-arch]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the version
        id: get_version
        run: echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get previous tag
        id: previous_tag
        run: |
          previous_tag=$(git describe --tags --abbrev=0 ${{ github.ref }}^ 2>/dev/null || echo "")
          echo "previous_tag=$previous_tag" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Generate Release Body
        id: generate_release_body
        run: |
          {
            echo "body<<EOF"
            if [ -n "${{ steps.previous_tag.outputs.previous_tag }}" ]; then
              git log --pretty=format:"- %s" ${{ steps.previous_tag.outputs.previous_tag }}..${{ github.ref }}
            else
              git log --pretty=format:"- %s" ${{ github.ref }}
            fi
            echo ""
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.get_version.outputs.version }}
          body: |
            ## Release ${{ steps.get_version.outputs.version }}

            This release includes the following changes:

            ${{ steps.generate_release_body.outputs.body }}
          draft: false
          prerelease: false
          files: |
            artifacts/source-tarball/securepasswd_mgmt-${{ steps.get_version.outputs.version }}.tar.gz
            artifacts/debian-package/*.deb
            artifacts/arch-package/*.pkg.tar.zst
            artifacts/windows-installer/*.exe
            artifacts/macos-dmg/*.dmg
